/* Contenu du site : tout ce qui change souvent vit ici. */
const IMG = 'https://clicodeal.mg/images/product-images/';

window.HNA = {
  config: {
    // Numéro affiché sur le catalogue clicodeal. À confirmer : doit être le numéro WhatsApp de la boutique.
    whatsapp: '261380809981',
    phoneDisplay: '+261 38 08 099 81',
    email: 'ExpressHNA@gmail.com',
    maps: 'https://maps.app.goo.gl/sEGXjjfoDDxQv1Qv7',
    instagram: 'https://www.instagram.com/hna_parfumerie',
    facebook: 'https://www.facebook.com/share/19nwvrMsA3/',
    tiktok: 'https://www.tiktok.com/@hna_parfumerie',
    whatsappGroup: 'https://chat.whatsapp.com/KTiiVilViS8CvSk2l9SLWN',
    logo: 'https://clicodeal.mg/images/users/1731305708.jpeg',
  },

  // Références mises en avant dans l'éventail du haut de page.
  featured: ['DOSE', 'VDBRED', 'GVIT', 'JPGSP', 'FBKR'],

  families: [
    { key: 'floral', label: 'Floral' },
    { key: 'boise', label: 'Boisé' },
    { key: 'oriental', label: 'Oriental' },
    { key: 'gourmand', label: 'Gourmand' },
    { key: 'fruite', label: 'Fruité' },
    { key: 'frais', label: 'Frais' },
  ],

  products: [
    {
      sku: 'DOSE', brand: 'Dior', name: 'Sauvage Elixir', type: 'Eau de parfum', gender: 'Homme', size: '60 ml',
      price: 450000, origin: 'Paris', accord: 'Aromatique, épicé, boisé', families: ['boise', 'frais'],
      desc: 'Une intensité profonde et élégante : des épices chaudes et une lavande puissante, pour un caractère fort et charismatique.',
      notes: { tete: ['Cannelle', 'Muscade', 'Cardamome', 'Pamplemousse'], coeur: ['Lavande'], fond: ['Bois de santal', 'Réglisse', 'Patchouli', 'Ambre', 'Vétiver'] },
      img: IMG + '01763966755.jpeg',
    },
    {
      sku: 'VDBRED', brand: 'Valentino', name: 'Donna Born in Roma Extradose', type: 'Eau de parfum', gender: 'Femme', size: null,
      price: 692000, origin: null, accord: 'Oriental vanillé', families: ['oriental', 'gourmand'],
      desc: 'La douceur de la vanille mêlée à l’intensité du jasmin : un sillage chaud et élégant, au caractère affirmé.',
      notes: { tete: ['Cassis'], coeur: ['Rhum'], fond: ['Vanille'] },
      img: IMG + '01760698999.jpeg',
    },
    {
      sku: 'GVIT', brand: 'Givenchy', name: 'L’Interdit', type: 'Eau de parfum', gender: 'Femme', size: '50 ml',
      price: 400000, origin: 'Paris', accord: 'Floral, boisé, musqué', families: ['floral', 'boise'],
      desc: 'Une déclaration d’audace, une sensualité en clair-obscur qui intrigue et séduit à chaque sillage.',
      notes: { tete: ['Poire', 'Bergamote'], coeur: ['Tubéreuse', 'Fleur d’oranger', 'Jasmin sambac'], fond: ['Patchouli', 'Vanille', 'Ambroxan', 'Vétiver'] },
      img: IMG + '01763966646.jpeg',
    },
    {
      sku: 'JPGSP', brand: 'Jean Paul Gaultier', name: 'Scandal Le Parfum', type: 'Eau de parfum', gender: 'Homme', size: '100 ml',
      price: 458000, origin: 'France', accord: 'Oriental, ambré, gourmand', families: ['oriental', 'gourmand'],
      desc: 'Ultra sensuel et audacieux : la gourmandise d’une fleur de jasmin s’embrase dans un sillage enivrant de caramel salé et de vanille ambrée.',
      notes: { tete: ['Jasmin sambac'], coeur: ['Caramel salé'], fond: ['Vanille noire', 'Ambre'] },
      img: IMG + '01763966375.jpeg',
    },
    {
      sku: 'GCF', brand: 'Gucci', name: 'Flora', type: 'Eau de parfum', gender: 'Femme', size: '100 ml',
      price: 420000, origin: 'Paris', accord: 'Floral fruité', families: ['floral', 'fruite'],
      desc: 'Lumineux et pétillant. Inspiré par le gardénia, il allie fraîcheur florale et douceur sucrée pour une féminité joyeuse.',
      notes: { tete: ['Poire', 'Baies rouges', 'Mandarine italienne'], coeur: ['Gardénia blanc', 'Jasmin', 'Frangipanier'], fond: ['Patchouli', 'Sucre brun', 'Bois de santal'] },
      img: IMG + '01763966580.jpeg',
    },
    {
      sku: 'FBKR', brand: 'Kenzo', name: 'Flower by Kenzo Le Rouge', type: 'Eau de parfum', gender: 'Femme', size: '50 ml',
      price: 490000, origin: 'Paris', accord: 'Floral gourmand', families: ['floral', 'gourmand'],
      desc: 'Réconfortant et sensuel : la douceur d’un accord vapeur de riz, une rose majestueuse, un fond chaud de vanille et de santal.',
      notes: { tete: ['Muscs enveloppants', 'Vapeur de riz'], coeur: ['Rose damascena'], fond: ['Amberever', 'Vanille', 'Bois de santal'] },
      img: IMG + '01786344481.jpeg',
    },
    {
      sku: 'PYEA', brand: 'Emporio Armani', name: 'Power of You', type: 'Eau de toilette', gender: 'Femme', size: '90 ml',
      price: 731000, origin: 'Paris', accord: 'Floral, fruité, gourmand', families: ['floral', 'fruite', 'gourmand'],
      desc: 'Addictif et gourmand, dans un flacon-bijou aux reflets rubis. Une féminité audacieuse, du matin au soir.',
      notes: { tete: ['Fruit de la passion', 'Orange amère', 'Citron'], coeur: ['Frangipanier', 'Notes solaires'], fond: ['Vanille de Madagascar', 'Benjoin', 'Labdanum'] },
      img: IMG + '01774504281.jpeg',
    },
    {
      sku: 'GCGI', brand: 'Gucci', name: 'Guilty Intense', type: 'Eau de parfum', gender: 'Femme', size: '50 ml',
      price: 680000, origin: 'Paris', accord: 'Floral oriental', families: ['floral', 'oriental'],
      desc: 'La sensualité à l’état pur : audacieux et envoûtant, pour une femme sûre d’elle, prête à séduire sans s’excuser.',
      notes: { tete: ['Poivre rose', 'Mandarine'], coeur: ['Lilas', 'Violette', 'Héliotrope'], fond: ['Ambre', 'Patchouli'] },
      img: IMG + '01750061831.jpeg',
    },
    {
      sku: 'LCF', brand: 'Lacoste', name: 'Pour Femme', type: 'Eau de parfum', gender: 'Femme', size: '90 ml',
      price: 568000, origin: 'Paris', accord: 'Floral fruité', families: ['floral', 'fruite', 'frais'],
      desc: 'La fraîcheur sportive alliée à l’élégance citronnée : une douceur vibrante, légère et éclatante au quotidien.',
      notes: { tete: ['Citron', 'Orange', 'Poire'], coeur: ['Fleur d’oranger', 'Fleur de tiaré'], fond: ['Bois blancs', 'Musc'] },
      img: IMG + '01763966452.jpeg',
    },
    {
      sku: 'LTMR', brand: 'Lancôme', name: 'Trésor Midnight Rose', type: 'Eau de parfum', gender: 'Femme', size: '50 ml',
      price: 368000, origin: 'Paris', accord: 'Floral boisé', families: ['floral', 'boise', 'fruite'],
      desc: 'Gourmande et envoûtante : la fraîcheur fruitée de la framboise, une rose intense, un fond chaleureux de vanille et de cèdre.',
      notes: { tete: ['Framboise', 'Rose'], coeur: ['Cassis', 'Pivoine', 'Jasmin', 'Poivre rose'], fond: ['Vanille', 'Cèdre de Virginie', 'Musc'] },
      img: IMG + '01786344033.jpeg',
    },
    {
      sku: 'GVIR', brand: 'Givenchy', name: 'Irresistible', type: 'Eau de parfum', gender: 'Femme', size: '80 ml',
      price: 400000, origin: 'Paris', accord: 'Floral, boisé, fruité', families: ['floral', 'boise', 'fruite'],
      desc: 'Doux, lumineux et séduisant : parfait pour le quotidien comme pour les moments élégants.',
      notes: { tete: ['Poire', 'Ambrette'], coeur: ['Rose', 'Iris'], fond: ['Musc', 'Cèdre de Virginie'] },
      img: IMG + '01763967128.jpeg',
    },
    {
      sku: 'JPGIH', brand: 'Jean Paul Gaultier', name: 'Scandal Pour Homme Intense', type: 'Eau de parfum', gender: 'Homme', size: '50 ml',
      price: 458000, origin: 'Paris', accord: 'Boisé aromatique', families: ['boise'],
      desc: 'Ultra sensuel et magnétique, dans son flacon torsadé iconique. Une virilité brute et addictive, un charisme absolu.',
      notes: { tete: ['Sauge sclarée'], coeur: ['Vétiver'], fond: ['Cuir'] },
      img: IMG + '01776666092.jpeg',
    },
    {
      sku: 'ERC', brand: 'Rochas', name: 'Eau de Rochas', type: 'Eau de toilette', gender: 'Femme', size: '100 ml',
      price: 354000, origin: 'Paris', accord: 'Hespéridé, frais', families: ['frais'],
      desc: 'Une fragrance mythique, vivante et cristalline, entre fraîcheur et sophistication. Créée en 1970, toujours aussi moderne.',
      notes: { tete: ['Citron vert', 'Basilic', 'Bergamote', 'Pamplemousse', 'Mandarine', 'Verveine'], coeur: ['Coriandre', 'Patchouli', 'Œillet', 'Narcisse', 'Jasmin', 'Églantier'], fond: ['Mousse de chêne', 'Vétiver', 'Musc', 'Bois de santal', 'Ambre'] },
      img: IMG + '01749643446.jpeg',
    },
    {
      sku: 'CKEM', brand: 'Calvin Klein', name: 'Euphoria Men', type: 'Eau de toilette', gender: 'Homme', size: '100 ml',
      price: 288000, origin: 'Paris', accord: 'Boisé épicé', families: ['boise', 'frais'],
      desc: 'Frais et addictif : le gingembre poivré, un cœur aromatique de basilic noir, un fond sensuel de daim et de séquoia.',
      notes: { tete: ['Gingembre poivré', 'Accord de sudachi'], coeur: ['Basilic noir', 'Feuille de cèdre', 'Sauge'], fond: ['Daim', 'Séquoia', 'Ambre', 'Patchouli'] },
      img: IMG + '01786344385.jpeg',
    },
    {
      sku: 'Ckone', brand: 'Calvin Klein', name: 'CK One', type: 'Eau de toilette', gender: 'Mixte', size: '100 ml',
      price: 230000, origin: 'Paris', accord: 'Hespéridé aromatique', families: ['frais'],
      desc: 'Un intemporel qui va à tout le monde : un sillage frais, élégant et confiant, mémorable toute la journée.',
      notes: { tete: ['Citron', 'Notes vertes', 'Bergamote', 'Mandarine', 'Ananas', 'Cardamome', 'Papaye'], coeur: ['Muguet', 'Jasmin', 'Violette', 'Rose', 'Noix de muscade', 'Freesia', 'Iris'], fond: ['Accord vert', 'Musc', 'Cèdre', 'Thé vert', 'Santal', 'Mousse de chêne', 'Ambre'] },
      img: IMG + '01773905562.jpeg',
    },
    {
      sku: 'CkBT', brand: 'Calvin Klein', name: 'Beauty', type: 'Eau de parfum', gender: 'Femme', size: '50 ml',
      price: 238000, origin: 'Paris', accord: 'Floral', families: ['floral'],
      desc: 'Une élégance pure, une grâce intemporelle qui sublime la féminité avec raffinement.',
      notes: { tete: ['Ambrette'], coeur: ['Jasmin'], fond: ['Cèdre de Virginie'] },
      img: IMG + '01773905848.jpeg',
    },
    {
      sku: 'Ckin2uher', brand: 'Calvin Klein', name: 'CK IN2U Her', type: 'Eau de toilette', gender: 'Femme', size: '100 ml',
      price: 195000, origin: 'Paris', accord: 'Oriental floral', families: ['oriental', 'floral'],
      desc: 'Moderne, séduisant et irrésistiblement sensuel, pour une femme sûre d’elle, douce et pleine de charme.',
      notes: { tete: ['Pamplemousse rose'], coeur: ['Cactus', 'Orchidée'], fond: ['Vanille', 'Cèdre rouge', 'Ambre'] },
      img: IMG + '01773906369.jpeg',
    },
    {
      sku: 'TCM', brand: 'Tangaur', name: 'Celest for Men', type: 'Eau de parfum', gender: 'Homme', size: '100 ml',
      price: 95000, origin: 'Dubaï', accord: 'Floral fruité', families: ['floral', 'fruite'],
      desc: 'Très moderne, joyeux et masculin. Une tête fruitée, lumineuse et pétillante, puis un fond crémeux et sensuel.',
      notes: { tete: ['Mandarine', 'Pamplemousse', 'Poire verte', 'Gingembre', 'Pêche blanche'], coeur: [], fond: ['Nectar d’abricot', 'Bois de santal', 'Patchouli', 'Muscs blancs'] },
      img: IMG + '01725015782.jpeg',
    },
    {
      sku: 'T365M', brand: 'Tangaur', name: '365 Days Men', type: 'Eau de parfum', gender: 'Homme', size: '100 ml',
      price: 95000, origin: 'Dubaï', accord: null, families: [],
      desc: 'Une odeur puissante, et surtout bien à elle.',
      notes: null,
      img: IMG + '01725451780.jpeg',
    },
    {
      sku: 'TMH', brand: 'Tangaur', name: 'Macho', type: 'Eau de parfum', gender: 'Homme', size: '100 ml',
      price: 95000, origin: null, accord: null, families: [],
      desc: 'Très puissant et masculin.',
      notes: null,
      img: IMG + '01728477167.jpeg',
    },
    {
      sku: 'TCX', brand: 'Tangaur', name: 'Calyx', type: 'Eau de parfum', gender: 'Mixte', size: '100 ml',
      price: 95000, origin: 'Dubaï', accord: null, families: [],
      desc: 'Homme ou femme, rien ne change : Calyx va aussi bien à l’un qu’à l’autre.',
      notes: null,
      img: IMG + '01725453890.jpeg',
    },
    {
      sku: 'T365W', brand: 'Tangaur', name: '365 Days for Women', type: 'Eau de parfum', gender: 'Femme', size: '100 ml',
      price: 95000, origin: 'Dubaï', accord: null, families: [],
      desc: 'Une eau de parfum magnifique.',
      notes: null,
      img: IMG + '01725623716.jpeg',
    },
    {
      sku: 'TCW', brand: 'Tangaur', name: 'Celeste Women', type: 'Eau de parfum', gender: 'Femme', size: '100 ml',
      price: 95000, origin: 'Dubaï', accord: null, families: [],
      desc: 'Une odeur céleste.',
      notes: null,
      img: IMG + '01725623870.jpeg',
    },
  ],
};
